spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_service
    username: jboss_dt_user
    password: jboss_dt_pass
    driver-class-name: org.postgresql.Driver
    maximum-pool-size: 5
    connection-timeout: 60000
    initFailTimeout: 60
  liquibase:
    default-schema: public
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  application:
    name: payment-service
server:
  port: 8082

springdoc:
  swagger-ui:
    path: /swagger
