spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/account_service
    username: jboss_dt_user
    password: jboss-dt-pass
    driver-class-name: org.postgresql.Driver
    minimum-idle: 5
  liquibase:
    default-schema: account_schema
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  application:
    name: account-service
server:
  port: 8081
